version: '3'
services:
  prisma:
    image: prismagraphql/prisma:1.12
    restart: always
    ports:
      - '4466:4466'
    environment:
      PRISMA_CONFIG: |
        port: 4466
        # uncomment the next line and provide the env var PRISMA_MANAGEMENT_API_SECRET=my-secret to activate cluster security
        # managementApiSecret: my-secret
        databases:
          default:
            connector: postgres
            host: ec2-23-23-195-205.compute-1.amazonaws.com
            port: '5432'
            database: d8lh1ki3o65drh
            ssl: true
            user: ifinypdwollhqf
            password: 98227fa178d078a4954656bf72a6c90cbe5cad801f731a12ecd7b988477706cd
            migrations: true
